// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC-8V0Rjap7gE6SEvTLqYj-C0Okp7N6gg',
    appId: '1:1023087039032:web:854a48b0c4dadd5cdd8ccd',
    messagingSenderId: '1023087039032',
    projectId: 'rental-app-49bde',
    authDomain: 'rental-app-49bde.firebaseapp.com',
    storageBucket: 'rental-app-49bde.firebasestorage.app',
    measurementId: 'G-M7WELTXW46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Aqd_smJO7v99TbuAOYDwqIwSFbm6Nqk',
    appId: '1:1023087039032:android:4a709b80abbb51b0dd8ccd',
    messagingSenderId: '1023087039032',
    projectId: 'rental-app-49bde',
    storageBucket: 'rental-app-49bde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaYZ_hU-oL4vKc35lQV-iyguCK76miX-Y',
    appId: '1:1023087039032:ios:5e7b43fa8bd8985add8ccd',
    messagingSenderId: '1023087039032',
    projectId: 'rental-app-49bde',
    storageBucket: 'rental-app-49bde.firebasestorage.app',
    iosBundleId: 'com.example.rentalAppartment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaYZ_hU-oL4vKc35lQV-iyguCK76miX-Y',
    appId: '1:1023087039032:ios:5e7b43fa8bd8985add8ccd',
    messagingSenderId: '1023087039032',
    projectId: 'rental-app-49bde',
    storageBucket: 'rental-app-49bde.firebasestorage.app',
    iosBundleId: 'com.example.rentalAppartment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC-8V0Rjap7gE6SEvTLqYj-C0Okp7N6gg',
    appId: '1:1023087039032:web:e5e437425d6cd128dd8ccd',
    messagingSenderId: '1023087039032',
    projectId: 'rental-app-49bde',
    authDomain: 'rental-app-49bde.firebaseapp.com',
    storageBucket: 'rental-app-49bde.firebasestorage.app',
    measurementId: 'G-H3JEPT9GER',
  );
}
